coverage:
  range: '50..70'
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%

comment:
  layout: 'reach,diff,flags,files'
  behavior: default
  require_changes: true

ignore:
  - 'dist/'
  - 'coverage/'
  - 'test/'
  - 'templates/'
  - 'docs/'
